### ISSUE TITLE
[Styling] Article search bar

### ISSUE THREAD

**Issue by amirhouieh** [acid-info/logos-press-engine#204]
### Summary:

- [x] When dragging down the article page, we see the search bar comes down 
- [x] When search bar is open, it does not fully go over the sidebar label. We need to either cover it completely or not covering it at all

https://github.com/acid-info/logos-press-engine/assets/7159454/5c9927ed-999f-423f-9929-59b06a255f34

**Comment by nireims** [comment]
@jeangovil can you make the default state of the search box 46-48px so it covers the 'contents' label?
