### ISSUE TITLE
Image carousel is not there

### ISSUE THREAD

**Issue by amirhouieh** [acid-info/logos-press-engine#27]

**Comment by jinhojang6** [comment]
ETA: May 15

**Comment by amirhouieh** [comment]
@jinhojang6 lets put this in backlog if you have not started with

**Comment by jinhojang6** [comment]
Okay

**Comment by jongomez** [comment]
Implemented a lightbox variation like the one on vac.dev - it's not a full carousel, but for the moment this was what people asked for. Closing for now, but if a new fully fledge lightbox carousel component is necessary, please don't hesitate on creating a new issue.
